-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  package_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  traveler_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  weight_kg numeric NOT NULL,
  total_price numeric NOT NULL,
  currency character varying DEFAULT 'EUR'::character varying,
  payment_method character varying,
  payment_intent_id character varying,
  status USER-DEFINED DEFAULT 'pending'::booking_status,
  confirmed_at timestamp with time zone,
  paid_at timestamp with time zone,
  picked_up_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT bookings_package_id_fkey FOREIGN KEY (package_id) REFERENCES public.packages(id),
  CONSTRAINT bookings_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT bookings_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.users(id)
);
CREATE TABLE public.cities (
  id integer NOT NULL DEFAULT nextval('cities_id_seq'::regclass),
  name character varying NOT NULL,
  country_id integer,
  latitude numeric,
  longitude numeric,
  is_major_city boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cities_pkey PRIMARY KEY (id),
  CONSTRAINT cities_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid,
  type USER-DEFINED DEFAULT 'booking'::conversation_type,
  participant_1_id uuid NOT NULL,
  participant_2_id uuid NOT NULL,
  is_active boolean DEFAULT true,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_participant_2_id_fkey FOREIGN KEY (participant_2_id) REFERENCES public.users(id),
  CONSTRAINT conversations_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT conversations_participant_1_id_fkey FOREIGN KEY (participant_1_id) REFERENCES public.users(id)
);
CREATE TABLE public.countries (
  id integer NOT NULL DEFAULT nextval('countries_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  code character varying NOT NULL UNIQUE,
  flag_emoji character varying,
  region character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT countries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  conversation_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  content text NOT NULL CHECK (TRIM(BOTH FROM content) <> ''::text),
  message_type character varying DEFAULT 'text'::character varying,
  attachment_url text,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  is_edited boolean DEFAULT false,
  edited_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  booking_id uuid,
  trip_id uuid,
  message_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  push_sent boolean DEFAULT false,
  push_sent_at timestamp with time zone,
  email_sent boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT notifications_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT notifications_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id)
);
CREATE TABLE public.packages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sender_id uuid NOT NULL,
  trip_id uuid,
  title character varying NOT NULL,
  description text NOT NULL,
  weight_kg numeric NOT NULL CHECK (weight_kg > 0::numeric),
  dimensions character varying CHECK (dimensions::text ~ '^\d+x\d+x\d+cm$'::text OR dimensions IS NULL),
  estimated_value numeric,
  currency character varying DEFAULT 'EUR'::character varying,
  recipient_name character varying NOT NULL,
  recipient_phone character varying NOT NULL,
  recipient_address text NOT NULL,
  recipient_city_id integer NOT NULL,
  content_category USER-DEFINED NOT NULL,
  is_fragile boolean DEFAULT false,
  contains_liquid boolean DEFAULT false,
  contains_electronics boolean DEFAULT false,
  delivery_instructions text,
  requires_signature boolean DEFAULT true,
  status USER-DEFINED DEFAULT 'pending'::package_status,
  tracking_number character varying,
  photos ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT packages_pkey PRIMARY KEY (id),
  CONSTRAINT packages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.users(id),
  CONSTRAINT packages_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT packages_recipient_city_id_fkey FOREIGN KEY (recipient_city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL,
  payer_id uuid NOT NULL,
  payee_id uuid NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency character varying NOT NULL DEFAULT 'EUR'::character varying,
  payment_method character varying NOT NULL,
  stripe_payment_intent_id character varying,
  stripe_charge_id character varying,
  external_transaction_id character varying,
  status USER-DEFINED DEFAULT 'pending'::payment_status,
  processed_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  platform_fee numeric DEFAULT 0,
  payment_fee numeric DEFAULT 0,
  net_amount numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_payee_id_fkey FOREIGN KEY (payee_id) REFERENCES public.users(id),
  CONSTRAINT payments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT payments_payer_id_fkey FOREIGN KEY (payer_id) REFERENCES public.users(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  booking_id uuid NOT NULL,
  reviewer_id uuid NOT NULL,
  reviewee_id uuid NOT NULL,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  title character varying,
  comment text,
  communication_rating integer CHECK (communication_rating >= 1 AND communication_rating <= 5),
  reliability_rating integer CHECK (reliability_rating >= 1 AND reliability_rating <= 5),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_reviewer_id_fkey FOREIGN KEY (reviewer_id) REFERENCES public.users(id),
  CONSTRAINT reviews_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT reviews_reviewee_id_fkey FOREIGN KEY (reviewee_id) REFERENCES public.users(id)
);
CREATE TABLE public.spatial_ref_sys (
  srid integer NOT NULL CHECK (srid > 0 AND srid <= 998999),
  auth_name character varying,
  auth_srid integer,
  srtext character varying,
  proj4text character varying,
  CONSTRAINT spatial_ref_sys_pkey PRIMARY KEY (srid)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  traveler_id uuid NOT NULL,
  from_city_id integer NOT NULL,
  to_city_id integer NOT NULL,
  departure_date date NOT NULL CHECK (departure_date >= CURRENT_DATE),
  return_date date,
  available_weight_kg numeric NOT NULL CHECK (available_weight_kg > 0::numeric),
  reserved_weight_kg numeric DEFAULT 0,
  price_per_kg numeric NOT NULL CHECK (price_per_kg > 0::numeric),
  currency character varying DEFAULT 'EUR'::character varying,
  is_price_negotiable boolean DEFAULT false,
  title character varying NOT NULL,
  description text,
  special_instructions text,
  contact_phone character varying,
  contact_whatsapp character varying,
  is_available boolean DEFAULT true,
  status USER-DEFINED DEFAULT 'planned'::trip_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_to_city_id_fkey FOREIGN KEY (to_city_id) REFERENCES public.cities(id),
  CONSTRAINT trips_from_city_id_fkey FOREIGN KEY (from_city_id) REFERENCES public.cities(id),
  CONSTRAINT trips_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  device_id character varying,
  device_info jsonb,
  push_token character varying,
  is_active boolean DEFAULT true,
  last_activity timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email character varying NOT NULL CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  phone character varying,
  avatar_url text,
  date_of_birth date,
  gender character varying,
  address text,
  city character varying,
  country character varying,
  postal_code character varying,
  id_document_url text,
  is_verified boolean DEFAULT false,
  verification_date timestamp with time zone,
  preferred_language character varying DEFAULT 'fr'::character varying,
  preferred_currency character varying DEFAULT 'EUR'::character varying,
  role USER-DEFINED NOT NULL DEFAULT 'both'::user_role,
  status USER-DEFINED DEFAULT 'pending_verification'::user_status,
  total_trips integer DEFAULT 0,
  total_packages_sent integer DEFAULT 0,
  average_rating numeric DEFAULT 0.0 CHECK (average_rating >= 0::numeric AND average_rating <= 5::numeric),
  total_reviews integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
